#to execute docker yml file run "docker-compose -f <filename> up"
#add -d to the end to detach execution

version: "3.9"
services:
     selenium-hub:
     image: selenium/hub:latest
     container_name: selenium hub
     restart: always
     poprts:
     - "4444:4444"  #for multiple values
     
     chrome:
     image: selenium/node-chrome:latest
     volumes: 
     - dev/shm:/dev/shm
     depends_on: selenium hub
     envoirnment:
     - HUB_HOST=selenium hub
     - HUB_PORT=4444
     restart: on-failure:3
     
      
     firefox:
     image: selenium/node-firefox:latest
     volumes: 
     - dev/shm:/dev/shm
     depends_on: selenium hub
     envoirnment:
     - HUB_HOST=selenium hub
     - HUB_PORT=4444
     restart: on-failure:3
     
     
     

